# Generated by Django 2.1.1 on 2018-10-27 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0005_auto_20181009_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('yearin', models.DateField()),
                ('yearout', models.DateField()),
                ('slug', models.SlugField(blank=True, default='')),
                ('gardengroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.GardenGroup')),
            ],
        ),
    ]
