# Generated by Django 2.1.1 on 2018-10-27 20:08

from django.db import migrations, models
import django.db.models.deletion
import garden.models


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0007_auto_20181027_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, default='', max_length=200)),
                ('date_of_birth', models.DateField()),
                ('growth', models.PositiveIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('image', models.ImageField(upload_to=garden.models.generate_file_name)),
                ('slug', models.SlugField(blank=True, default='')),
                ('active', models.BooleanField(default=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('actual_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.Group')),
            ],
        ),
    ]
