# Generated by Django 2.1.1 on 2018-10-27 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('garden', '0008_children'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(blank=True, default='', max_length=200)),
                ('date_of_birth', models.DateField()),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('address', models.CharField(default='', max_length=250)),
                ('work', models.CharField(default='', max_length=250)),
                ('workplace', models.CharField(default='', max_length=90)),
                ('with_child', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='children',
            name='address',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='parent',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='garden.Children'),
        ),
    ]
